config/routes.rb
require 'resque_web'

PostAll::Application.routes.draw do

  # I like having this to populate the navbar with, via the database rather than do it in the views.
  resources :navbar_entries

  # Logins and Profiles
  devise_for :users

  get 'redirect/:src' => 'redirect_maps#redirect'
  resources :redirect_maps, only: [:create, :show, :new, :index]
  
  # Adds RailsAdmin
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  root to: 'redirect_maps#index'

  # Need a catch all to redirect to the errors controller, for catching 404s as an exception
  match "*path", to: "errors#catch_404", via: [:get, :post]

end

app/models/navbar_entry.rb
class NavbarEntry < ActiveRecord::Base
end

app/controllers/navbar_entries_controller.rb
class NavbarEntriesController < ApplicationController
  before_action :set_navbar_entry, only: [:show, :edit, :update, :destroy]

  # GET /navbar_entries
  # GET /navbar_entries.json
  def index
    @navbar_entries = NavbarEntry.all
  end

  # GET /navbar_entries/1
  # GET /navbar_entries/1.json
  def show
  end

  # GET /navbar_entries/new
  def new
    @navbar_entry = NavbarEntry.new
  end

  # GET /navbar_entries/1/edit
  def edit
  end

  # POST /navbar_entries
  # POST /navbar_entries.json
  def create
    @navbar_entry = NavbarEntry.new(navbar_entry_params)

    respond_to do |format|
      if @navbar_entry.save
        format.html { redirect_to @navbar_entry, notice: 'Navbar entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @navbar_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @navbar_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /navbar_entries/1
  # PATCH/PUT /navbar_entries/1.json
  def update
    respond_to do |format|
      if @navbar_entry.update(navbar_entry_params)
        format.html { redirect_to @navbar_entry, notice: 'Navbar entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @navbar_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navbar_entries/1
  # DELETE /navbar_entries/1.json
  def destroy
    @navbar_entry.destroy
    respond_to do |format|
      format.html { redirect_to navbar_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_navbar_entry
      @navbar_entry = NavbarEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def navbar_entry_params
      params.require(:navbar_entry).permit(:title, :url)
    end
end

app/views/navbar_entries/_form.html.haml
= form_for @navbar_entry do |f|
  - if @navbar_entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@navbar_entry.errors.count, "error")} prohibited this navbar_entry from being saved:"
      %ul
        - @navbar_entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/navbar_entries/edit.html.haml
%h1 Editing navbar_entry

= render 'form'

= link_to 'Show', @navbar_entry
\|
= link_to 'Back', navbar_entries_path

app/views/navbar_entries/index.html.haml
%h1 Listing navbar_entries

%table
  %tr
    %th Title
    %th Url
    %th
    %th
    %th

  - @navbar_entries.each do |navbar_entry|
    %tr
      %td= navbar_entry.title
      %td= navbar_entry.url
      %td= link_to 'Show', navbar_entry
      %td= link_to 'Edit', edit_navbar_entry_path(navbar_entry)
      %td= link_to 'Destroy', navbar_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Navbar entry', new_navbar_entry_path

app/views/navbar_entries/new.html.haml
%h1 New navbar_entry

= render 'form'

= link_to 'Back', navbar_entries_path

app/views/navbar_entries/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @navbar_entry.title
%p
  %b Url:
  = @navbar_entry.url

= link_to 'Edit', edit_navbar_entry_path(@navbar_entry)
\|
= link_to 'Back', navbar_entries_path